#!/usr/bin/env Rscript

#pcoa test script
options(error=recover)

library(ape)
library(phangorn)

# commenting out incorrect clr dirichlet

# get default par
plotParameters <- par()


#this weightedUnifrac script was ripped straight from the weightedUnifrac package, with no changes.
source("../../GUnifrac.R")

source("../../InformationUniFrac.R")


# read OTU table and format appropriately for input into UniFrac methods
data.otu.tab <- read.table("./master_table_knight.txt", header=T, sep="\t", row.names=1, comment.char="", check.names=FALSE)
taxa <- rownames(data.otu.tab)
data.otu.tab <- apply(data.otu.tab,2,as.numeric)
rownames(data.otu.tab) <- taxa

#remove taxonomy column to make otu count matrix numeric
taxonomy <- rownames(data.otu.tab)
#data.otu.tab <- data.otu.tab[-length(colnames(data.otu.tab))]
data.otu.tab <- t(as.matrix(data.otu.tab))

#sort taxa from most to least abundant
taxaOrder <- rev(order(apply(data.otu.tab,2,sum)))
taxonomy <- taxonomy[taxaOrder]
data.otu.tab <- data.otu.tab[,taxaOrder]

# read and root tree (rooted tree is required)
data.tree <- read.tree("./gg_13_5_unannotated.tre")
data.tree <- midpoint(data.tree)

# read metadata
MyMeta<- read.table("./meta_analysis_table_oct30_2014 - meta_analysis_table_feb19_fixed.tsv", header=T, sep="\t", row.names=1, comment.char="", check.names=FALSE)

#remove infected sample S38I
#MyMeta <- MyMeta[(which(rownames(MyMeta)!="S38I")),]

# filter OTU table and metadata so that only samples which appear in both are retained
otu_indicies <- match(rownames(MyMeta),rownames(data.otu.tab))
otu_indicies <- otu_indicies[!is.na(otu_indicies)]
data.otu.tab <- data.otu.tab[otu_indicies,]
MyMetaOrdered <- MyMeta[match(rownames(data.otu.tab),rownames(MyMeta)),]

#remove all samples with one or less OTU
hasOneOrLessOTU <- function(data) {
	if(length(which(data!=0))<=1) {
		return(TRUE)
	}
	return(FALSE)
}

oneOrLessOTUSamples <- apply(data.otu.tab,1,hasOneOrLessOTU)
moreThanOneOTUSamples <- which(oneOrLessOTUSamples==FALSE)
oneOrLessOTUSamples <- which(oneOrLessOTUSamples==TRUE)
if (length(oneOrLessOTUSamples)>0) {
	data.otu.tab <- data.otu.tab[moreThanOneOTUSamples,]
}


# #get bray curtis distance matrix
# bcdm <- stats:::as.matrix.dist(vegdist(data.otu.tab))

# write.table(data.frame(bcdm),file="BrayCurtisDistanceMatrix.txt",append=FALSE,quote=FALSE,sep="\t")

bcdm <- read.table("BrayCurtisDistanceMatrix.txt",sep="\t",row.names=1)


#clrDirichletUniFrac <- CLRDirichletUniFrac(data.otu.tab, data.tree, alpha = c(1))$unifrac[,,1]

#conditions (bv - bacterial vaginosis as scored by nugent/amsel, i - intermediate, n - normal/healthy)
# groups <- MyMetaOrdered$Gestation #levels ""    "G"   "P_a" "P_b" "T" 
# originalgroups <- groups
# levels(groups) <- c(levels(groups),"Infected")
# groups[which(rownames(MyMetaOrdered)=="S38I")] <- levels(groups)[6]

adultInfantGroups <- MyMetaOrdered$ADULT_INFANT
bodySiteGroups <- MyMetaOrdered$SAMPLE_TYPE

groups <- paste(as.character(adultInfantGroups),as.character(bodySiteGroups))

groups <- as.factor(groups)

otuSum <- apply(data.otu.tab,1,sum)


# # change conditions so that samples which are more than 50% one taxa are colored by that taxa
# otuMax <- apply(data.otu.tab,1,max)
# otuWhichMax <- apply(data.otu.tab,1,which.max)
# otuDominated <- which(otuMax > otuSum/2)


# otuMaxTax <- taxonomy[otuWhichMax]
# otuDominated <- c(otuDominated[which(as.numeric(otuMaxTax[otuDominated])==32)],otuDominated[which(as.numeric(otuMaxTax[otuDominated])==33)])

# taxonomyGroups <- as.character(groups)
# taxonomyGroups[otuDominated] <- as.character(otuMaxTax[otuDominated])
# taxonomyGroups <- as.factor(taxonomyGroups)

# groups <- taxonomyGroups

# # assign appropriate names to single taxa dominated groups
# newLevels <- levels(taxonomyGroups)
# splittaxa <- strsplit(levels(taxonomyGroups),split=";")

# for (i in 1:length(splittaxa)) {
# 	if (length(splittaxa[[i]])>1) {
# 		newLevels[i] <- paste("L.",splittaxa[[i]][length(splittaxa[[i]])])
# 	}
# 	else {
# 		newLevels[i] <- splittaxa[[i]][1]
# 	}
# }

# levels(taxonomyGroups) <- newLevels

# caculate pcoa vectors
bc.pcoa <- pcoa(bcdm)

# calculate total variance explained
bc.varExplained <- sum(apply(bc.pcoa$vector,2,function(x) sd(x)*sd(x)))

# calculate proportion of variance explained by first component
bc.pc1.varEx <- sd(bc.pcoa$vector[,1])*sd(bc.pcoa$vector[,1])/bc.varExplained
#calculate proportion of variance explained by second component
bc.pc2.varEx <- sd(bc.pcoa$vector[,2])*sd(bc.pcoa$vector[,2])/bc.varExplained
bc.pc3.varEx <- sd(bc.pcoa$vector[,3])*sd(bc.pcoa$vector[,3])/bc.varExplained


#save plots as PDF
pdf("megan_data_bray_curtis_plots.pdf")


# MAKE BAR PLOTS

# #convert to dist structure
# unweightedUnifrac.dist <- as.dist(unweightedUnifrac)
# weightedUnifrac.dist <- as.dist(weightedUnifrac)
# eUnifrac.dist <- as.dist(eUnifrac)

# #"average" is most similar to UPGMA, apparently
# unweightedUnifrac.dendo <- hclust(unweightedUnifrac.dist, method="average")
# weightedUnifrac.dendo <- hclust(weightedUnifrac.dist, method="average")
# eUnifrac.dendo <- hclust(eUnifrac.dist, method="average")

# #get otu proportions for barplot
# brazil.prop <- t(apply(data.otu.tab,1,function(x) x/sum(x)))

#plot dendogram with bar plots

# #GG legacy code. Fix size, margins, position
# par(mfrow=c(2,1), mar=c(1, 3, 2, 1) + 0.1,cex=0.3)

# plot(unweightedUnifrac.dendo, axes=F, ylab=NULL, ann=F,hang=-1)

# #order the barplot 
# colors <- c("steelblue3","skyblue1", "indianred1", "mediumpurple1", "olivedrab3", "pink", "#FFED6F", "mediumorchid3", "ivory2", "tan1", "aquamarine3", "#C0C0C0", "royalblue4", "mediumvioletred", "#999933", "#666699", "#CC9933", "#006666", "#3399FF", "#993300", "#CCCC99", "#666666", "#FFCC66", "#6699CC", "#663366", "#9999CC", "#CCCCCC", "#669999", "#CCCC66", "#CC6600", "bisque", "#9999FF", "#0066CC", "#99CCCC", "#999999", "#FFCC00", "#009999", "#FF9900", "#999966", "#66CCCC", "#339966", "#CCCC33", "#EDEDED")
# barplot(t(brazil.prop[unweightedUnifrac.dendo$order,]), space=0,col=colors, las=2)

# plot(weightedUnifrac.dendo, axes=F, ylab=NULL, ann=F)
# #order the barplot 
# barplot(t(brazil.prop[weightedUnifrac.dendo$order,]), space=0,col=colors, las=2)

# plot(eUnifrac.dendo, axes=F, ylab=NULL, ann=F)
# #order the barplot 
# barplot(t(brazil.prop[eUnifrac.dendo$order,]), space=0,col=colors, las=2)

#plot(clrDirichletUniFrac.dendo, axes=F, ylab=NULL, ann=F)
#order the barplot 
#barplot(t(brazil.prop[clrDirichletUniFrac.dendo$order,]), space=0,col=colors, las=2)

#par(plotParameters)



#choose colors for each condition
palette(c("red","black","cyan","dodgerblue","blue","orange"))





#plot pcoa plots with legend
plot(bc.pcoa$vectors[,1],bc.pcoa$vectors[,2], type="p",col=groups,main="Bray Curtis\nprincipal coordinate analysis",xlab=paste("First Component", round(bc.pc1.varEx,digits=3),"variance explained"),ylab=paste("Second Component", round(bc.pc2.varEx,digits=3),"variance explained"),pch=19,cex.lab=1.4,cex.main=2)
legend(0,0,levels(groups),col=palette(),pch=19)
#placement with S38I included
#legend(-0.1,-0.055,levels(groups),col=palette(),pch=19)
# #placement with S38I excluded
# legend(0.055,0.15,levels(groups),col=palette(),pch=19)

plot(bc.pcoa$vectors[,2],bc.pcoa$vectors[,3], type="p",col=groups,main="Bray Curtis\nprincipal coordinate analysis",xlab=paste("Second Component", round(bc.pc2.varEx,digits=3),"variance explained"),ylab=paste("Third Component", round(bc.pc3.varEx,digits=3),"variance explained"),pch=19,cex.lab=1.4,cex.main=2)

plot(bc.pcoa$vectors[,1],bc.pcoa$vectors[,3], type="p",col=groups,main="Bray Curtis\nprincipal coordinate analysis",xlab=paste("First Component", round(bc.pc1.varEx,digits=3),"variance explained"),ylab=paste("Third Component", round(bc.pc3.varEx,digits=3),"variance explained"),pch=19,cex.lab=1.4,cex.main=2)


dev.off()